### ISSUE TITLE
dating of WGD

### ISSUE THREAD

**Issue by okokookk** [MaoYafei/Genome-duplication-calculation#2]
I am using this pipeline to analyze WGD. This pipeline is a great help for me. Thank you for building such a pipeline. 
But I have a problem that I can not solve.
Can you tell me how to check the dating of WGD after using this pipeline?

I am going to analyze the dating of WGD with reference to the paper below.
"A Likely Ancient Genome Duplication in theSpeciose Reef-Building Coral Genus,Acropora"

I have a hard time understanding the methods perfectly.
Are there any pipelines or tutorials that can calculate age of WGD using dS-based method or phylogenomic analysis?
If you have the scripts that you used in the above paper, can you give me so that I can analyze them using the scripts?
If you can't do that and you can send me the six cds fasta used in the above paper, I'll use it to study.

I look forward to your reply. 
Thank you

**Comment by MaoYafei** [comment]
Hi, 

Thank you for your interest in GenoDup.

For phylogenomic analysis, I reconstructed each gene family tree by hand using BEAST2 and extracted the node values. Then, I got a list of age nodes and I used KDE function to estimate the mean and SD. Same as dS-based methods. You could check the KDE function here (https://www.mathworks.com/help/stats/ksdensity.html). 

Also, you might be interested in this tool (https://bitbucket.org/barkerlab/maps/src/master/).

Best,
Yafei
